"""Add procedure management tables

Revision ID: 448035aecd81
Revises: 2302595cc0fb
Create Date: 2025-10-27 05:34:10.543197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448035aecd81'
down_revision: Union[str, None] = '2302595cc0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedures_id'), 'procedures', ['id'], unique=False)
    op.create_index(op.f('ix_procedures_name'), 'procedures', ['name'], unique=False)
    op.create_table('procedure_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedure_products_id'), 'procedure_products', ['id'], unique=False)
    op.add_column('invoice_lines', sa.Column('procedure_id', sa.Integer(), nullable=True))
    op.alter_column('invoice_lines', 'service_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'invoice_lines', 'procedures', ['procedure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_lines', type_='foreignkey')
    op.alter_column('invoice_lines', 'service_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('invoice_lines', 'procedure_id')
    op.drop_index(op.f('ix_procedure_products_id'), table_name='procedure_products')
    op.drop_table('procedure_products')
    op.drop_index(op.f('ix_procedures_name'), table_name='procedures')
    op.drop_index(op.f('ix_procedures_id'), table_name='procedures')
    op.drop_table('procedures')
    # ### end Alembic commands ###
