"""add icd10 tables

Revision ID: 33b1aa81beab
Revises: 31d71d368572
Create Date: 2025-10-29 00:05:43.051060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b1aa81beab'
down_revision: Union[str, None] = '31d71d368572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_record_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinical_record_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('is_autosave', sa.Boolean(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinical_record_id'], ['clinical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_record_versions_clinical_record_id'), 'clinical_record_versions', ['clinical_record_id'], unique=False)
    op.create_index(op.f('ix_clinical_record_versions_id'), 'clinical_record_versions', ['id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinical_record_id', sa.Integer(), nullable=False),
    sa.Column('cid_code', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('PRIMARY', 'SECONDARY', name='diagnosistype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinical_record_id'], ['clinical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_clinical_record_id'), 'diagnoses', ['clinical_record_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_id'), 'diagnoses', ['id'], unique=False)
    op.add_column('clinical_records', sa.Column('plan_soap', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_records', 'plan_soap')
    op.drop_index(op.f('ix_diagnoses_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_clinical_record_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_clinical_record_versions_id'), table_name='clinical_record_versions')
    op.drop_index(op.f('ix_clinical_record_versions_clinical_record_id'), table_name='clinical_record_versions')
    op.drop_table('clinical_record_versions')
    # ### end Alembic commands ###
