"""Add clinical tables

Revision ID: 2c5a29af25b5
Revises: 4be369f65f48
Create Date: 2025-10-26 00:15:30.938338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5a29af25b5'
down_revision: Union[str, None] = '4be369f65f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subjective', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_records_appointment_id'), 'clinical_records', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_clinical_records_id'), 'clinical_records', ['id'], unique=False)
    op.create_table('exam_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinical_record_id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('urgency', sa.Enum('ROUTINE', 'URGENT', 'EMERGENCY', name='urgencylevel'), nullable=False),
    sa.Column('requested_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinical_record_id'], ['clinical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_requests_clinical_record_id'), 'exam_requests', ['clinical_record_id'], unique=False)
    op.create_index(op.f('ix_exam_requests_id'), 'exam_requests', ['id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinical_record_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('issued_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinical_record_id'], ['clinical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_clinical_record_id'), 'prescriptions', ['clinical_record_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_clinical_record_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_exam_requests_id'), table_name='exam_requests')
    op.drop_index(op.f('ix_exam_requests_clinical_record_id'), table_name='exam_requests')
    op.drop_table('exam_requests')
    op.drop_index(op.f('ix_clinical_records_id'), table_name='clinical_records')
    op.drop_index(op.f('ix_clinical_records_appointment_id'), table_name='clinical_records')
    op.drop_table('clinical_records')
    # ### end Alembic commands ###
