"""add icd10 comprehensive tables

Revision ID: 182de6f89ae4
Revises: 2a77b43d4b6f
Create Date: 2025-10-29 04:19:15.589424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182de6f89ae4'
down_revision: Union[str, None] = '2a77b43d4b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icd10_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_short', sa.String(length=200), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('exclusions', sa.Text(), nullable=True),
    sa.Column('group_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icd10_categories_code'), 'icd10_categories', ['code'], unique=True)
    op.create_index('ix_icd10_categories_group', 'icd10_categories', ['group_code'], unique=False)
    op.create_index(op.f('ix_icd10_categories_group_code'), 'icd10_categories', ['group_code'], unique=False)
    op.create_index(op.f('ix_icd10_categories_id'), 'icd10_categories', ['id'], unique=False)
    op.create_table('icd10_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_short', sa.String(length=200), nullable=True),
    sa.Column('start_code', sa.String(length=10), nullable=True),
    sa.Column('end_code', sa.String(length=10), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_icd10_chapters_code', 'icd10_chapters', ['code'], unique=False)
    op.create_index(op.f('ix_icd10_chapters_id'), 'icd10_chapters', ['id'], unique=False)
    op.create_table('icd10_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_short', sa.String(length=200), nullable=True),
    sa.Column('chapter_code', sa.String(length=10), nullable=True),
    sa.Column('start_code', sa.String(length=10), nullable=True),
    sa.Column('end_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_icd10_groups_chapter', 'icd10_groups', ['chapter_code'], unique=False)
    op.create_index(op.f('ix_icd10_groups_chapter_code'), 'icd10_groups', ['chapter_code'], unique=False)
    op.create_index('ix_icd10_groups_code', 'icd10_groups', ['code'], unique=False)
    op.create_index(op.f('ix_icd10_groups_id'), 'icd10_groups', ['id'], unique=False)
    op.create_table('icd10_search_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('parent_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icd10_search_index_code'), 'icd10_search_index', ['code'], unique=False)
    op.create_index(op.f('ix_icd10_search_index_id'), 'icd10_search_index', ['id'], unique=False)
    op.create_index(op.f('ix_icd10_search_index_parent_code'), 'icd10_search_index', ['parent_code'], unique=False)
    op.create_index('ix_icd10_search_level', 'icd10_search_index', ['level'], unique=False)
    op.create_index('ix_icd10_search_text', 'icd10_search_index', ['search_text'], unique=False)
    op.create_table('icd10_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_short', sa.String(length=200), nullable=True),
    sa.Column('sex_restriction', sa.String(length=50), nullable=True),
    sa.Column('cause_of_death', sa.Boolean(), nullable=False),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('exclusions', sa.Text(), nullable=True),
    sa.Column('category_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_icd10_subcategories_category', 'icd10_subcategories', ['category_code'], unique=False)
    op.create_index(op.f('ix_icd10_subcategories_category_code'), 'icd10_subcategories', ['category_code'], unique=False)
    op.create_index('ix_icd10_subcategories_code', 'icd10_subcategories', ['code'], unique=False)
    op.create_index('ix_icd10_subcategories_death', 'icd10_subcategories', ['cause_of_death'], unique=False)
    op.create_index(op.f('ix_icd10_subcategories_id'), 'icd10_subcategories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_icd10_subcategories_id'), table_name='icd10_subcategories')
    op.drop_index('ix_icd10_subcategories_death', table_name='icd10_subcategories')
    op.drop_index('ix_icd10_subcategories_code', table_name='icd10_subcategories')
    op.drop_index(op.f('ix_icd10_subcategories_category_code'), table_name='icd10_subcategories')
    op.drop_index('ix_icd10_subcategories_category', table_name='icd10_subcategories')
    op.drop_table('icd10_subcategories')
    op.drop_index('ix_icd10_search_text', table_name='icd10_search_index')
    op.drop_index('ix_icd10_search_level', table_name='icd10_search_index')
    op.drop_index(op.f('ix_icd10_search_index_parent_code'), table_name='icd10_search_index')
    op.drop_index(op.f('ix_icd10_search_index_id'), table_name='icd10_search_index')
    op.drop_index(op.f('ix_icd10_search_index_code'), table_name='icd10_search_index')
    op.drop_table('icd10_search_index')
    op.drop_index(op.f('ix_icd10_groups_id'), table_name='icd10_groups')
    op.drop_index('ix_icd10_groups_code', table_name='icd10_groups')
    op.drop_index(op.f('ix_icd10_groups_chapter_code'), table_name='icd10_groups')
    op.drop_index('ix_icd10_groups_chapter', table_name='icd10_groups')
    op.drop_table('icd10_groups')
    op.drop_index(op.f('ix_icd10_chapters_id'), table_name='icd10_chapters')
    op.drop_index('ix_icd10_chapters_code', table_name='icd10_chapters')
    op.drop_table('icd10_chapters')
    op.drop_index(op.f('ix_icd10_categories_id'), table_name='icd10_categories')
    op.drop_index(op.f('ix_icd10_categories_group_code'), table_name='icd10_categories')
    op.drop_index('ix_icd10_categories_group', table_name='icd10_categories')
    op.drop_index(op.f('ix_icd10_categories_code'), table_name='icd10_categories')
    op.drop_table('icd10_categories')
    # ### end Alembic commands ###
