"""add_licensing_fields_to_clinic

Revision ID: d00a7fe9fd05
Revises: 448035aecd81
Create Date: 2025-10-28 00:16:03.306110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00a7fe9fd05'
down_revision: Union[str, None] = '448035aecd81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('license_key', sa.String(length=100), nullable=True))
    op.add_column('clinics', sa.Column('expiration_date', sa.Date(), nullable=True))
    op.add_column('clinics', sa.Column('max_users', sa.Integer(), nullable=True))
    op.add_column('clinics', sa.Column('active_modules', sa.JSON(), nullable=True))
    
    # Set default values for existing clinics
    op.execute("UPDATE clinics SET max_users = 10 WHERE max_users IS NULL")
    op.execute("UPDATE clinics SET active_modules = '[]' WHERE active_modules IS NULL")
    
    # Now make max_users NOT NULL
    op.alter_column('clinics', 'max_users', nullable=False)
    
    op.create_index(op.f('ix_clinics_license_key'), 'clinics', ['license_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinics_license_key'), table_name='clinics')
    op.drop_column('clinics', 'active_modules')
    op.drop_column('clinics', 'max_users')
    op.drop_column('clinics', 'expiration_date')
    op.drop_column('clinics', 'license_key')
    # ### end Alembic commands ###
