"""add icd10 tables

Revision ID: 2a77b43d4b6f
Revises: 33b1aa81beab
Create Date: 2025-10-29 04:10:16.512490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a77b43d4b6f'
down_revision: Union[str, None] = '33b1aa81beab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
